version: 2

jobs:
  build:
    docker:
      - image: headspace/hs-node:8.9 # primary container
        environment:
          NODE_ENV: test
          TEST_FAIL_ON_ERROR: true
          TSLINT_FAIL_ON_ERROR: true
    working_directory: ~/proxy
    steps:
      - checkout

      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            yarn

      - run:
          name: Run tests
          command: |
            yarn test:unit && yarn test:integration

      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "~/.yarn-cache"

      - store_artifacts:
          path: coverage/

      - store_test_results:
          path: test-output/

      - add_ssh_keys

      - deploy:
          name: Maybe publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm publish
            fi

experimental:
  notify:
    branches:
      only:
        - master
        - develop
