version: 2

jobs:
  build:
    docker:
      - image: headspace/hs-node:10.13.0 # primary container
        environment:
          NODE_ENV: test
    working_directory: ~/zuora-request-service
    steps:
      - checkout

      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            yarn

      - run:
          name: Run tests
          command: |
            yarn test:coverage

      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "~/.yarn-cache"

      - store_artifacts:
          path: coverage/

      - store_test_results:
          path: report/

      - add_ssh_keys

      - deploy:
          name: Maybe publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm publish
            fi

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build:
          context: org-global

experimental:
  notify:
    branches:
      only:
        - master
